package com.pruebalombok.model;
/**
 * This class was automatically generated by the data modeler tool.
 */
public class Persona implements java.io.Serializable {
	static final long serialVersionUID = 1L;
	private java.lang.String nombre;
	private java.lang.String apellido;

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getApellido() {
		return this.apellido;
	}

	public void setApellido(java.lang.String apellido) {
		this.apellido = apellido;
	}

	public Persona() {
	}

	public Persona(java.lang.String nombre, java.lang.String apellido) {
		this.nombre = nombre;
		this.apellido = apellido;
	}
}