package com.pruebalombok.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * This class was automatically generated by the data modeler tool.
 */
@Getter @Setter @NoArgsConstructor
public class Persona implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String nombre;
	private java.lang.String apellido;

	public Persona() {
	}

	public Persona(java.lang.String nombre, java.lang.String apellido) {
		this.nombre = nombre;
		this.apellido = apellido;
	}

}