package com.pruebalombok.model;
import lombok.Data;
/**
 * This class was automatically generated by the data modeler tool.
 */
public class @Data Persona implements java.io.Serializable {
	static final long serialVersionUID = 1L;
	private java.lang.String nombre;
	private java.lang.String apellido;

}